// Map ZMK key names to actual characters
export const ZMK_CHAR_MAP: Record<string, string> = {
  EXCL: '!',
  EXCLAMATION: '!',
  AT: '@',
  AT_SIGN: '@',
  HASH: '#',
  POUND: '#',
  DOLLAR: '$',
  DLLR: '$',
  PERCENT: '%',
  PRCNT: '%',
  CARET: '^',
  AMPS: '&',
  AMPERSAND: '&',
  ASTERISK: '*',
  ASTRK: '*',
  STAR: '*',
  LEFT_PARENTHESIS: '(',
  LPAR: '(',
  RIGHT_PARENTHESIS: ')',
  RPAR: ')',
  LEFT_BRACKET: '[',
  LBKT: '[',
  RIGHT_BRACKET: ']',
  RBKT: ']',
  LEFT_BRACE: '{',
  LBRC: '{',
  RIGHT_BRACE: '}',
  RBRC: '}',
  MINUS: '-',
  PLUS: '+',
  EQUAL: '=',
  UNDER: '_',
  UNDERSCORE: '_',
  PIPE: '|',
  BACKSLASH: '\\',
  BSLH: '\\',
  SLASH: '/',
  FSLH: '/',
  SEMICOLON: ';',
  SEMI: ';',
  COLON: ':',
  SQT: "'",
  SINGLE_QUOTE: "'",
  DQT: '"',
  DOUBLE_QUOTES: '"',
  COMMA: ',',
  PERIOD: '.',
  DOT: '.',
  GRAVE: '`',
  TILDE: '~',
  LT: '<',
  LESS_THAN: '<',
  GT: '>',
  GREATER_THAN: '>',
  QUESTION: '?',
  QMARK: '?',
  // Number keys
  N0: '0',
  N1: '1',
  N2: '2',
  N3: '3',
  N4: '4',
  N5: '5',
  N6: '6',
  N7: '7',
  N8: '8',
  N9: '9',
  NUMBER_0: '0',
  NUMBER_1: '1',
  NUMBER_2: '2',
  NUMBER_3: '3',
  NUMBER_4: '4',
  NUMBER_5: '5',
  NUMBER_6: '6',
  NUMBER_7: '7',
  NUMBER_8: '8',
  NUMBER_9: '9',
}

export function zmkToChar(name: string): string | null {
  if (name in ZMK_CHAR_MAP) return ZMK_CHAR_MAP[name]
  if (/^[A-Z]$/.test(name)) return name.toLowerCase()
  return null
}
